spring.application.name=ms-gestion-guias
server.port=8080

# EFS montado desde Docker/EC2. En local se puede cambiar a ./efs
app.efs.path=${EFS_PATH:/app/efs}

# Bucket S3 usado para guardar las guias
app.s3.bucket=${S3_BUCKET:bucket-guias-despacho}
app.aws.region=${AWS_REGION:us-east-1}
